version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
    environment:
      - TZ=Iran/Tehran
    restart: always
    network_mode: host
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./.db/mqtt/data:/mosquitto/data
      - ./.db/mqtt/log:/mosquitto/log/mosquitto.log
